version: '3'

volumes:
  grafana_data:

networks:
  monitoring-networks:
    driver: bridge

services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        nertworks:
            - monitoring-networks
        depends_on:
            - prometheus
    
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.enable-lifecycle'
        depends_on:
            - snmp-exporter
        networks:
            monitoring-networks

    snmp-exporter:
        image: prom/snmp-exporter:latest
        container_name: snmp
        ports:
            - "9116:9116"
        volumes:
            - ./snmp/snmp.yml:/etc/snmp_exporter/snmp.yml
        networks:
            - monitoring-networks