global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 192.168.18.101:9100
        labels:
          app: prometheus

  - job_name: 'frr-exporter'
    static_configs:
      - targets:
          - 192.168.18.101:9342
        labels:
          app: frr

  - job_name: 'mikrotik-exporter'
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [mikrotik]
    static_configs:
      - targets:
          - 192.168.18.99
    relabel_configs:
      - source_labels: [__param_module]
        target_label: module
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: snmp-exporter:9117

  - job_name: 'snmp-exporter'
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    static_configs:
      - targets:
          - 192.168.18.99
          - 192.168.18.101:161
    relabel_configs:
      - source_labels: [__param_module]
        target_label: module
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: snmp-exporter:9116
